// source: services/job/service.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var github_com_oojob_protobuf_place_pb = require('../../github.com/oojob/protobuf/place_pb.js');
goog.object.extend(proto, github_com_oojob_protobuf_place_pb);
var github_com_oojob_protobuf_metadata_pb = require('../../github.com/oojob/protobuf/metadata_pb.js');
goog.object.extend(proto, github_com_oojob_protobuf_metadata_pb);
var github_com_oojob_protobuf_time_pb = require('../../github.com/oojob/protobuf/time_pb.js');
goog.object.extend(proto, github_com_oojob_protobuf_time_pb);
var github_com_oojob_protobuf_system_pb = require('../../github.com/oojob/protobuf/system_pb.js');
goog.object.extend(proto, github_com_oojob_protobuf_system_pb);
var github_com_oojob_protobuf_health_pb = require('../../github.com/oojob/protobuf/health_pb.js');
goog.object.extend(proto, github_com_oojob_protobuf_health_pb);
var github_com_oojob_protobuf_applicants_pb = require('../../github.com/oojob/protobuf/applicants_pb.js');
goog.object.extend(proto, github_com_oojob_protobuf_applicants_pb);
goog.exportSymbol('proto.job.CreateJobReq', null, global);
goog.exportSymbol('proto.job.CreateJobRes', null, global);
goog.exportSymbol('proto.job.Job', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.job.Job = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.job.Job.repeatedFields_, null);
};
goog.inherits(proto.job.Job, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.job.Job.displayName = 'proto.job.Job';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.job.CreateJobReq = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.job.CreateJobReq, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.job.CreateJobReq.displayName = 'proto.job.CreateJobReq';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.job.CreateJobRes = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.job.CreateJobRes, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.job.CreateJobRes.displayName = 'proto.job.CreateJobRes';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.job.Job.repeatedFields_ = [6,9];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.job.Job.prototype.toObject = function(opt_includeInstance) {
  return proto.job.Job.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.job.Job} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.job.Job.toObject = function(includeInstance, msg) {
  var f, obj = {
    identity: (f = msg.getIdentity()) && github_com_oojob_protobuf_system_pb.Identifier.toObject(includeInstance, f),
    employment: jspb.Message.getFieldWithDefault(msg, 2, ""),
    salary: (f = msg.getSalary()) && github_com_oojob_protobuf_system_pb.Range.toObject(includeInstance, f),
    experience: (f = msg.getExperience()) && github_com_oojob_protobuf_system_pb.Range.toObject(includeInstance, f),
    time: (f = msg.getTime()) && github_com_oojob_protobuf_time_pb.Time.toObject(includeInstance, f),
    skillsList: (f = jspb.Message.getRepeatedField(msg, 6)) == null ? undefined : f,
    workingHours: jspb.Message.getFieldWithDefault(msg, 7, ""),
    status: jspb.Message.getFieldWithDefault(msg, 8, ""),
    qualificationList: (f = jspb.Message.getRepeatedField(msg, 9)) == null ? undefined : f,
    place: (f = msg.getPlace()) && github_com_oojob_protobuf_place_pb.Place.toObject(includeInstance, f),
    metadata: (f = msg.getMetadata()) && github_com_oojob_protobuf_metadata_pb.Metadata.toObject(includeInstance, f),
    applicants: (f = msg.getApplicants()) && github_com_oojob_protobuf_applicants_pb.Applicant.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.job.Job}
 */
proto.job.Job.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.job.Job;
  return proto.job.Job.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.job.Job} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.job.Job}
 */
proto.job.Job.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new github_com_oojob_protobuf_system_pb.Identifier;
      reader.readMessage(value,github_com_oojob_protobuf_system_pb.Identifier.deserializeBinaryFromReader);
      msg.setIdentity(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setEmployment(value);
      break;
    case 3:
      var value = new github_com_oojob_protobuf_system_pb.Range;
      reader.readMessage(value,github_com_oojob_protobuf_system_pb.Range.deserializeBinaryFromReader);
      msg.setSalary(value);
      break;
    case 4:
      var value = new github_com_oojob_protobuf_system_pb.Range;
      reader.readMessage(value,github_com_oojob_protobuf_system_pb.Range.deserializeBinaryFromReader);
      msg.setExperience(value);
      break;
    case 5:
      var value = new github_com_oojob_protobuf_time_pb.Time;
      reader.readMessage(value,github_com_oojob_protobuf_time_pb.Time.deserializeBinaryFromReader);
      msg.setTime(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.addSkills(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setWorkingHours(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setStatus(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.addQualification(value);
      break;
    case 10:
      var value = new github_com_oojob_protobuf_place_pb.Place;
      reader.readMessage(value,github_com_oojob_protobuf_place_pb.Place.deserializeBinaryFromReader);
      msg.setPlace(value);
      break;
    case 11:
      var value = new github_com_oojob_protobuf_metadata_pb.Metadata;
      reader.readMessage(value,github_com_oojob_protobuf_metadata_pb.Metadata.deserializeBinaryFromReader);
      msg.setMetadata(value);
      break;
    case 12:
      var value = new github_com_oojob_protobuf_applicants_pb.Applicant;
      reader.readMessage(value,github_com_oojob_protobuf_applicants_pb.Applicant.deserializeBinaryFromReader);
      msg.setApplicants(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.job.Job.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.job.Job.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.job.Job} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.job.Job.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getIdentity();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      github_com_oojob_protobuf_system_pb.Identifier.serializeBinaryToWriter
    );
  }
  f = message.getEmployment();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getSalary();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      github_com_oojob_protobuf_system_pb.Range.serializeBinaryToWriter
    );
  }
  f = message.getExperience();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      github_com_oojob_protobuf_system_pb.Range.serializeBinaryToWriter
    );
  }
  f = message.getTime();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      github_com_oojob_protobuf_time_pb.Time.serializeBinaryToWriter
    );
  }
  f = message.getSkillsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      6,
      f
    );
  }
  f = message.getWorkingHours();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getStatus();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getQualificationList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      9,
      f
    );
  }
  f = message.getPlace();
  if (f != null) {
    writer.writeMessage(
      10,
      f,
      github_com_oojob_protobuf_place_pb.Place.serializeBinaryToWriter
    );
  }
  f = message.getMetadata();
  if (f != null) {
    writer.writeMessage(
      11,
      f,
      github_com_oojob_protobuf_metadata_pb.Metadata.serializeBinaryToWriter
    );
  }
  f = message.getApplicants();
  if (f != null) {
    writer.writeMessage(
      12,
      f,
      github_com_oojob_protobuf_applicants_pb.Applicant.serializeBinaryToWriter
    );
  }
};


/**
 * optional github.com.oojob.protobuf.Identifier identity = 1;
 * @return {?proto.github.com.oojob.protobuf.Identifier}
 */
proto.job.Job.prototype.getIdentity = function() {
  return /** @type{?proto.github.com.oojob.protobuf.Identifier} */ (
    jspb.Message.getWrapperField(this, github_com_oojob_protobuf_system_pb.Identifier, 1));
};


/**
 * @param {?proto.github.com.oojob.protobuf.Identifier|undefined} value
 * @return {!proto.job.Job} returns this
*/
proto.job.Job.prototype.setIdentity = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.job.Job} returns this
 */
proto.job.Job.prototype.clearIdentity = function() {
  return this.setIdentity(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.job.Job.prototype.hasIdentity = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string employment = 2;
 * @return {string}
 */
proto.job.Job.prototype.getEmployment = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.job.Job} returns this
 */
proto.job.Job.prototype.setEmployment = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional github.com.oojob.protobuf.Range salary = 3;
 * @return {?proto.github.com.oojob.protobuf.Range}
 */
proto.job.Job.prototype.getSalary = function() {
  return /** @type{?proto.github.com.oojob.protobuf.Range} */ (
    jspb.Message.getWrapperField(this, github_com_oojob_protobuf_system_pb.Range, 3));
};


/**
 * @param {?proto.github.com.oojob.protobuf.Range|undefined} value
 * @return {!proto.job.Job} returns this
*/
proto.job.Job.prototype.setSalary = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.job.Job} returns this
 */
proto.job.Job.prototype.clearSalary = function() {
  return this.setSalary(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.job.Job.prototype.hasSalary = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional github.com.oojob.protobuf.Range experience = 4;
 * @return {?proto.github.com.oojob.protobuf.Range}
 */
proto.job.Job.prototype.getExperience = function() {
  return /** @type{?proto.github.com.oojob.protobuf.Range} */ (
    jspb.Message.getWrapperField(this, github_com_oojob_protobuf_system_pb.Range, 4));
};


/**
 * @param {?proto.github.com.oojob.protobuf.Range|undefined} value
 * @return {!proto.job.Job} returns this
*/
proto.job.Job.prototype.setExperience = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.job.Job} returns this
 */
proto.job.Job.prototype.clearExperience = function() {
  return this.setExperience(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.job.Job.prototype.hasExperience = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional github.com.oojob.protobuf.Time time = 5;
 * @return {?proto.github.com.oojob.protobuf.Time}
 */
proto.job.Job.prototype.getTime = function() {
  return /** @type{?proto.github.com.oojob.protobuf.Time} */ (
    jspb.Message.getWrapperField(this, github_com_oojob_protobuf_time_pb.Time, 5));
};


/**
 * @param {?proto.github.com.oojob.protobuf.Time|undefined} value
 * @return {!proto.job.Job} returns this
*/
proto.job.Job.prototype.setTime = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.job.Job} returns this
 */
proto.job.Job.prototype.clearTime = function() {
  return this.setTime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.job.Job.prototype.hasTime = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * repeated string skills = 6;
 * @return {!Array<string>}
 */
proto.job.Job.prototype.getSkillsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 6));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.job.Job} returns this
 */
proto.job.Job.prototype.setSkillsList = function(value) {
  return jspb.Message.setField(this, 6, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.job.Job} returns this
 */
proto.job.Job.prototype.addSkills = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 6, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.job.Job} returns this
 */
proto.job.Job.prototype.clearSkillsList = function() {
  return this.setSkillsList([]);
};


/**
 * optional string working_hours = 7;
 * @return {string}
 */
proto.job.Job.prototype.getWorkingHours = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.job.Job} returns this
 */
proto.job.Job.prototype.setWorkingHours = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional string status = 8;
 * @return {string}
 */
proto.job.Job.prototype.getStatus = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.job.Job} returns this
 */
proto.job.Job.prototype.setStatus = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};


/**
 * repeated string qualification = 9;
 * @return {!Array<string>}
 */
proto.job.Job.prototype.getQualificationList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 9));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.job.Job} returns this
 */
proto.job.Job.prototype.setQualificationList = function(value) {
  return jspb.Message.setField(this, 9, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.job.Job} returns this
 */
proto.job.Job.prototype.addQualification = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 9, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.job.Job} returns this
 */
proto.job.Job.prototype.clearQualificationList = function() {
  return this.setQualificationList([]);
};


/**
 * optional github.com.oojob.protobuf.Place place = 10;
 * @return {?proto.github.com.oojob.protobuf.Place}
 */
proto.job.Job.prototype.getPlace = function() {
  return /** @type{?proto.github.com.oojob.protobuf.Place} */ (
    jspb.Message.getWrapperField(this, github_com_oojob_protobuf_place_pb.Place, 10));
};


/**
 * @param {?proto.github.com.oojob.protobuf.Place|undefined} value
 * @return {!proto.job.Job} returns this
*/
proto.job.Job.prototype.setPlace = function(value) {
  return jspb.Message.setWrapperField(this, 10, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.job.Job} returns this
 */
proto.job.Job.prototype.clearPlace = function() {
  return this.setPlace(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.job.Job.prototype.hasPlace = function() {
  return jspb.Message.getField(this, 10) != null;
};


/**
 * optional github.com.oojob.protobuf.Metadata metadata = 11;
 * @return {?proto.github.com.oojob.protobuf.Metadata}
 */
proto.job.Job.prototype.getMetadata = function() {
  return /** @type{?proto.github.com.oojob.protobuf.Metadata} */ (
    jspb.Message.getWrapperField(this, github_com_oojob_protobuf_metadata_pb.Metadata, 11));
};


/**
 * @param {?proto.github.com.oojob.protobuf.Metadata|undefined} value
 * @return {!proto.job.Job} returns this
*/
proto.job.Job.prototype.setMetadata = function(value) {
  return jspb.Message.setWrapperField(this, 11, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.job.Job} returns this
 */
proto.job.Job.prototype.clearMetadata = function() {
  return this.setMetadata(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.job.Job.prototype.hasMetadata = function() {
  return jspb.Message.getField(this, 11) != null;
};


/**
 * optional github.com.oojob.protobuf.Applicant applicants = 12;
 * @return {?proto.github.com.oojob.protobuf.Applicant}
 */
proto.job.Job.prototype.getApplicants = function() {
  return /** @type{?proto.github.com.oojob.protobuf.Applicant} */ (
    jspb.Message.getWrapperField(this, github_com_oojob_protobuf_applicants_pb.Applicant, 12));
};


/**
 * @param {?proto.github.com.oojob.protobuf.Applicant|undefined} value
 * @return {!proto.job.Job} returns this
*/
proto.job.Job.prototype.setApplicants = function(value) {
  return jspb.Message.setWrapperField(this, 12, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.job.Job} returns this
 */
proto.job.Job.prototype.clearApplicants = function() {
  return this.setApplicants(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.job.Job.prototype.hasApplicants = function() {
  return jspb.Message.getField(this, 12) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.job.CreateJobReq.prototype.toObject = function(opt_includeInstance) {
  return proto.job.CreateJobReq.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.job.CreateJobReq} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.job.CreateJobReq.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    descriptioon: jspb.Message.getFieldWithDefault(msg, 2, ""),
    category: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.job.CreateJobReq}
 */
proto.job.CreateJobReq.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.job.CreateJobReq;
  return proto.job.CreateJobReq.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.job.CreateJobReq} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.job.CreateJobReq}
 */
proto.job.CreateJobReq.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescriptioon(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setCategory(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.job.CreateJobReq.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.job.CreateJobReq.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.job.CreateJobReq} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.job.CreateJobReq.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getDescriptioon();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getCategory();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.job.CreateJobReq.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.job.CreateJobReq} returns this
 */
proto.job.CreateJobReq.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string descriptioon = 2;
 * @return {string}
 */
proto.job.CreateJobReq.prototype.getDescriptioon = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.job.CreateJobReq} returns this
 */
proto.job.CreateJobReq.prototype.setDescriptioon = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string category = 3;
 * @return {string}
 */
proto.job.CreateJobReq.prototype.getCategory = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.job.CreateJobReq} returns this
 */
proto.job.CreateJobReq.prototype.setCategory = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.job.CreateJobRes.prototype.toObject = function(opt_includeInstance) {
  return proto.job.CreateJobRes.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.job.CreateJobRes} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.job.CreateJobRes.toObject = function(includeInstance, msg) {
  var f, obj = {
    status: jspb.Message.getBooleanFieldWithDefault(msg, 1, false),
    id: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.job.CreateJobRes}
 */
proto.job.CreateJobRes.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.job.CreateJobRes;
  return proto.job.CreateJobRes.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.job.CreateJobRes} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.job.CreateJobRes}
 */
proto.job.CreateJobRes.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setStatus(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.job.CreateJobRes.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.job.CreateJobRes.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.job.CreateJobRes} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.job.CreateJobRes.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getStatus();
  if (f) {
    writer.writeBool(
      1,
      f
    );
  }
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional bool status = 1;
 * @return {boolean}
 */
proto.job.CreateJobRes.prototype.getStatus = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 1, false));
};


/**
 * @param {boolean} value
 * @return {!proto.job.CreateJobRes} returns this
 */
proto.job.CreateJobRes.prototype.setStatus = function(value) {
  return jspb.Message.setProto3BooleanField(this, 1, value);
};


/**
 * optional string id = 2;
 * @return {string}
 */
proto.job.CreateJobRes.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.job.CreateJobRes} returns this
 */
proto.job.CreateJobRes.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


goog.object.extend(exports, proto.job);
